# Generated by Django 3.0.3 on 2020-10-26 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_picture', models.ImageField(upload_to='upload/')),
                ('agent_name', models.CharField(max_length=25)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('agent_phone', models.CharField(max_length=11, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_pic', models.ImageField(upload_to='upload')),
                ('cat_name', models.CharField(max_length=23, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='Dapo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=80)),
                ('service_content', models.CharField(max_length=234, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pictiure', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(choices=[('Mr.', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Prof', 'Prof'), ('Engr', 'Engr')], max_length=10, null=True)),
                ('description', models.TextField(null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_pic', models.ImageField(upload_to='upload/', verbose_name='Property Picture')),
                ('street_name', models.CharField(max_length=234)),
                ('city', models.CharField(max_length=234)),
                ('price', models.FloatField(max_length=234)),
                ('bedroom', models.PositiveIntegerField()),
                ('bathroom', models.PositiveIntegerField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('property_status', models.CharField(choices=[('RENT', 'RENT'), ('FOR SALE', 'FOR SALE')], max_length=24)),
                ('garage', models.PositiveIntegerField()),
                ('property_size', models.PositiveIntegerField()),
                ('cat', models.ManyToManyField(to='hose.Category', verbose_name='Property Category')),
                ('prop_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hose.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_pic', models.ImageField(upload_to='upload/', verbose_name='Blog Picture')),
                ('blog_title', models.CharField(max_length=344, null=True)),
                ('blog_content', models.TextField(max_length=500000, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
