# Generated by Django 3.0.5 on 2020-05-26 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_picture', models.ImageField(upload_to='upload/')),
                ('agent_name', models.CharField(max_length=25)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('agent_phone', models.CharField(max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_pic', models.ImageField(upload_to='upload/', verbose_name='Blog Picture')),
                ('blog_content', models.CharField(max_length=500)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=23, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=80)),
                ('service_content', models.CharField(max_length=234, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=234, unique=True)),
                ('email', models.CharField(max_length=234, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_pic', models.ImageField(upload_to='upload/', verbose_name='Property Picture')),
                ('street_name', models.CharField(max_length=234)),
                ('city', models.CharField(max_length=234)),
                ('price', models.FloatField(max_length=234)),
                ('bedroom', models.IntegerField()),
                ('bathroom', models.IntegerField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('property_status', models.CharField(choices=[('RENT', 'RENT'), ('SALE', 'SALE')], max_length=24)),
                ('garage', models.IntegerField()),
                ('property_size', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hose.User')),
            ],
        ),
    ]
