# Generated by Django 3.0.5 on 2020-05-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hose', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='cat',
            field=models.ManyToManyField(null=True, to='hose.Category'),
        ),
    ]
