# Generated by Django 3.0.5 on 2020-05-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hose', '0002_property_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_pic',
            field=models.ImageField(null=True, upload_to='upload'),
        ),
    ]
