# Generated by Django 3.0.5 on 2020-05-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hose', '0003_category_cat_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_title',
            field=models.CharField(max_length=344, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_status',
            field=models.CharField(choices=[('RENT', 'RENT'), ('FOR SALE', 'ROR SALE')], max_length=24),
        ),
    ]
