# Generated by Django 3.0.5 on 2020-05-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hose', '0005_auto_20200528_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_content',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
