# Generated by Django 3.0.5 on 2020-05-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hose', '0007_blog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_content',
            field=models.TextField(max_length=500000, null=True),
        ),
    ]
