# Generated by Django 3.0.8 on 2020-08-26 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hose', '0008_auto_20200530_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dapo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='UserProfile',
        ),
        migrations.AlterField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_pic',
            field=models.ImageField(default=1, upload_to='upload'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='cat',
            field=models.ManyToManyField(to='hose.Category'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_status',
            field=models.CharField(choices=[('RENT', 'RENT'), ('FOR SALE', 'FOR SALE')], max_length=24),
        ),
        migrations.AlterField(
            model_name='property',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
