# Generated by Django 3.1.1 on 2020-09-12 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hose', '0010_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='cat',
            field=models.ManyToManyField(to='hose.Category', verbose_name='Property Category'),
        ),
        migrations.AlterField(
            model_name='property',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hose.userprofile'),
        ),
    ]
