# Generated by Django 3.1.1 on 2020-11-04 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hose', '0014_auto_20200921_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='user',
            new_name='prop_user',
        ),
    ]
